er@front project]$ cat /opt/itu/templates/simple.job
#!/bin/bash

#SBATCH --job-name=cpu        # Job name
#SBATCH i--output=job.%j.out      # Name of output file (%j expands to jobId)
#SBATCH --cpus-per-task=16        # Schedule one core
#SBATCH --time=5:00:00          # Run time (hh:mm:ss) - run for one hour max
#SBATCH --partition=brown    # Run on either the Red or Brown queue

# Print out the hostname of the node the job is running on
hostname
